# Generated by Django 4.0.5 on 2022-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('origin_coord', models.CharField(max_length=200)),
                ('destination_coord', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('datasource', models.CharField(max_length=50)),
            ],
        ),
    ]
